 services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend:/go/src/myapp
    command: sh -c 'go mod tidy && air'
    depends_on:
      - mongodb
    environment:
      TZ: Asia/Tokyo
  mongodb:
    container_name: "mongodb"
    hostname: mongodb
    build:
      context: ./docker
      dockerfile: mongodb.Dockerfile
    ports:
      - "27017:27017"