version: '3.9'
services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend:/go/src/myapp
    command: "go run main.go"
    depends_on:
      - mongodb
    environment:
      TZ: Asia/Tokyo
  mongodb:
    container_name: "mongodb"
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
