name: Golangci-lint ReviewDog 

on:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: backend
          github_token: ${{ secrets.github_token }}
          go_version: ^1.22
          reporter: github-pr-review
          level: warning
